module ObjectiveFactory
export OptHistory, make_obj, best_feasible
using TASOPT
using Printf
include(__TASOPTindices__)
include(joinpath(__TASOPTroot__,"utils","sensitivity.jl"))

"""
Container type for contraint for optimization
Use the corresponding constructor for it as additional field_path needs to be generated when constructed
If lim_up, or lim_lo are set to nothing, then their constrain will not be activated. If both nothing, the whole constraint is placeholder
"""
mutable struct Constraint{T<:AbstractFloat}
    name::Expr #Expression for state to be extract (Ex. :(parg[igVfuel]), :(parm[imVfuel, :]), :(pare[ierhofuel_driven,:,:]), :(fuselage.layout.cross_section.radius))
    pen_sca::T #Penalty scale
    lim_up::Union{T,Nothing,Expr} #Upper limit, trigger maximum modifier
    lim_lo::Union{T,Nothing,Expr} #Lower limit, trigger minimum modifier
    value_max::T #The maximum value of the constrainted variable (Driven)
    value_min::T #The minimum value of the constrainted variable (Driven)
    penalty_up::T #The penalty from upper bound violation (Driven)
    penalty_lo::T #The penalty from lower bound violation (Driven)
    field_path::Union{Vector,Nothing} #Will be generated by constructor (Driven)
    index::Any #(Driven)
    eps_buff::T #fraction buffer add and subtract from the limit to avoid roundoff error induced constraint unsatisfication
end

"""
    Constraint(name::Expr; pen_sca::Real=1.0, lim_up::Union{Real,Nothing,Expr}=nothing, lim_lo::Union{Real,Nothing,Expr}=nothing, eps_buff::Real=0.0)

Constructor for the `Constraint` type

    `name`: Expression for state to be extract (Ex. :(parg[igVfuel]), :(parm[imVfuel, :]), :(pare[ierhofuel_driven,:,:]), :(fuselage.layout.cross_section.radius))
            Remember the parameters should be mission 1 parameters for sizing
    `pen_sca`: pen_sca * Wpay * fractional_exceed^2 -> added penalty ~ scale_of_PFEI
    `lim_up`: Upper limit, trigger maximum modifier if the value is an array
    `lim_lo`: Lower limit, This can be an `Expr` just like name, if the limit depends on solution. Such as the maximum takeoff weight and maximum fuel tank volume.
    `eps_buff:` fractional buffer used to check if value violate the constraint. Due to the iterative nature of sizing loop. Round off error can make near miss that always fail for example fuel volume constrain at R2.
"""
function Constraint(name::Expr; pen_sca::Real=1.0, 
                    lim_up::Union{Real,Nothing,Expr}=nothing, 
                    lim_lo::Union{Real,Nothing,Expr}=nothing,
                    eps_buff::Real=0.0)
    T = Float64
    field_path, index = format_params(expr_to_string(name))
    lim_up = (isnothing(lim_up) || (lim_up isa Expr)) ? lim_up : T(lim_up)
    lim_lo = (isnothing(lim_lo) || (lim_lo isa Expr)) ? lim_lo : T(lim_lo)
    (!isnothing(lim_up) && !(lim_up isa Expr)) && 
    (!isnothing(lim_lo) && !(lim_lo isa Expr)) && @assert(lim_up > lim_lo)
    pen_sca = T(pen_sca)
    eps_buff = T(eps_buff)
    @assert(pen_sca>=0.0)
    @assert(eps_buff>=0.0)
    return Constraint{T}(name, pen_sca, lim_up, lim_lo, T(NaN), T(NaN), zero(T), zero(T), field_path, index, eps_buff)
end

"""
Container type for parameters for optimization
Use the corresponding constructor for it as additional field_path needs to be generated when constructed
"""
mutable struct Parameter{T<:AbstractFloat}
    name::Expr #Expression for parameter (Ex. :(parg[igVfuel]), :(parm[imVfuel, :]), :(pare[ierhofuel_driven,:,:]), :(fuselage.layout.cross_section.radius))
    val::T #Either a initial guess val_0 will be used to stored the final optimized solution val_final
    bon_up::T #Upper bound for this parameter
    bon_lo::T #Lower bound
    d_val::T #Initial step size for this parameter
    field_path::Union{Vector,Nothing} #Will be generated by constructor (Driven)
    index::Any #(Driven)
end

"""
Constructor for the `Parameter` type
Parameter(name::Expr, val::Real, bon_up::Real, bon_lo::Real, d_val::Real)
    `name`: Expression for parameter (Ex. :(parg[igVfuel]), :(parm[imVfuel, :]), :(pare[ierhofuel_driven,:,:]), :(fuselage.layout.cross_section.radius))
            Remember the parameters should be mission 1 parameters for sizing
    `val`: a initial guess val_0 (Later will be overwritten into final optimized value)
    `bon_up`: Upper bound for this parameter (Maybe either gloabl bound or local bound)
    `bon_lo`: Lower bound
    `d_val`: Initial step size for this parameter
"""
function Parameter(name::Expr, val::Real, bon_up::Real, bon_lo::Real, d_val::Real)
    T = Float64
    field_path, index = format_params(expr_to_string(name))
    val = T(val) 
    bon_up = T(bon_up) 
    bon_lo = T(bon_lo) 
    d_val = T(d_val)
    @assert(bon_up>=val)
    @assert(val>=bon_lo)
    @assert(d_val>=0.0)
    return Parameter{T}(name, val, bon_up, bon_lo, d_val, field_path, index)
end

"""
Container type for the history of optimization
There is a trivial default construstor for it but typically it is returned by `make_obj` function
"""
mutable struct OptHistory{T<:AbstractFloat}
    test_param::Vector{Vector{T}}
    penalty::Vector{T}
    PFEI::Vector{T}
    violations::Vector{Vector{Constraint}}
end

"""Constructor for `OptHistory`"""
OptHistory() = OptHistory{Float64}(
    Vector{Vector{Float64}}(),
    Vector{Float64}(),
    Vector{Float64}(),
    Vector{Vector{Constraint}}()
)

"""
Container type for the mission requirement parameters
Use the corresponding constructor for it as additional field_path needs to be generated when constructed
"""
mutable struct Requirement{T<:Union{Real,AbstractArray{<:Real}}}
    name::Expr #Expression for requirement parameter (Ex. :(parg[igVfuel]), :(parm[imVfuel, :]), :(pare[ierhofuel_driven,:,:]), :(fuselage.layout.cross_section.radius))
    val::T #value to set
    field_path::Union{Vector,Nothing} #Will be generated by constructor (Driven)
    index::Any #(Driven)
end

"""
Constructor for the `Requirement` type
Requirement(name::Expr, val::Union{Real,AbstractArray{<:Real}})
    `name`: Expression for requirement parameter (Ex. :(parg[igVfuel]), :(parm[imVfuel, :]), :(pare[ierhofuel_driven,:,:]), :(fuselage.layout.cross_section.radius))
            Remember the parameters should be mission 1 parameters for sizing
    `val`: value you want to set into that parameter, accept broadcasting and elementwise assingment to an array.
"""
function Requirement(name::Expr, val::Union{Real,AbstractArray{<:Real}})
    field_path, index = format_params(expr_to_string(name))
    return Requirement{typeof(val)}(name,val,field_path,index)
end


"""
    best_feasible(hist_all::OptHistory)
`best_feasible` take a OptHistory and filter out a lowest penalty solution without violating any of the constraints

!!! details "🔃 Inputs and Outputs"
    **Inputs:**
        - `hist_all::OptHistory`: Optimization history

    **Outputs:**
        - nothing: if there were no feasible solution
        - named tuple (index, test_param, penalty, PFEI) for the best solution from the history
"""
function best_feasible(hist_all::OptHistory)
    idx = findall(v -> isempty(v), hist_all.violations)
    isempty(idx) && return nothing
    i = idx[argmin(hist_all.penalty[idx])]
    return (index=i, test_param=hist_all.test_param[i], penalty=hist_all.penalty[i], PFEI=hist_all.PFEI[i])
end
                              #Try to start with all 1 here actually
#penal_scale::Vector{Float64}=[25.0, 1.0, 1.0, 5.0, 5.0, 1.0, 10.0, 10.0]
#                       buffer[0     0    0      0   0.  0.  1e-4   1e-4]
#ac.wing.layout.span (Double check what goes in here)
#ac.parm[imlBF,1]
#ac.para[iagamV, ipclimbn, 1]
#maximum(ac.pare[ieTt3, :, 1])
#maximum(ac.pare[ieTmet1, :, 1])
#ac.parg[igdfan]
#ac.parm[imWTO, 1] -> ac.parg[igWMTO] as upper bound
#ac.parm[imVfuel, 1] -> ac.parg[igVfmax] as upper bound
#
#
#         ac.wing.layout.AR    = x[1]                                # Aspect Ratio 
#         ac.wing.layout.sweep = x[3]                                # Sweep angle (deg)
#         ac.wing.inboard.λ    = x[5]                                # Inner panel taper ratio
#         ac.wing.outboard.λ   = x[6]                                # Outer panel taper ratio
#         ac.wing.inboard.cross_section.thickness_to_chord  = x[7]   # Root thickness-to-chord ratio
#         ac.wing.outboard.cross_section.thickness_to_chord = x[8]   # Spanbreak thickness-to-chord ratio

#         # Update flight condition parameters
#         ac.para[iaCL, ipclimb1+1:ipdescentn-1, 1] .= x[2]       # Cruise lift coefficient
#         ac.para[iaalt, ipclimbn:ipcruise1, 1]     .= x[4]       # Cruise altitude
#         ac.para[iarcls, ipclimb2:ipdescent4, 1]   .= x[9]       # Break/root CL ratio = cls/clo
#         ac.para[iarclt, ipclimb2:ipdescent4, 1]   .= x[10]      # Tip/root CL ratio = clt/clo

#         # Update engine parameters
#         ac.pare[ieTt4, ipcruise1:ipcruise2, 1] .= x[11]         # Turbine inlet temperature
#         ac.pare[iepihc, ipcruise1, 1]           = x[12]         # High pressure compressor pressure ratio
#         ac.pare[iepif, ipcruise1, 1]            = x[13]         # Fan pressure ratio
#         ac.pare[iepilc, ipcruise1, 1]           = x[14]         # Low pressure compressor pressure ratio (fixed)
#         ac.pare[ieBPR, ipcruise1, 1]            = x[15]         # Bypass ratio
#     mission_req.range_des > 0 || throw(ArgumentError("Design flight range > 0"))
#     mission_req.rho_fuel > 0 || throw(ArgumentError("Fuel density > 0"))
#     mission_req.hvap_fuel >= 0 || throw(ArgumentError("Fuel heat of vaporization >= 0"))
#     # Constraints
#     constraints_opt.span_max > 0 || throw(ArgumentError("span_max > 0")) # Maximum span (m)
#     constraints_opt.lenField_max > 0 || throw(ArgumentError("lenField_max > 0")) # Maximum balanced field length (m)
#     constraints_opt.TOCGamma_min > 0 || throw(ArgumentError("TOCGamma_min > 0")) # Minimum top-of-climb flight angle (rad)
#     constraints_opt.Tt3_max > 0 || throw(ArgumentError("Tt3_max > 0")) # Maximum combustor inlet temperature (K)
#     constraints_opt.TMetal_max > 0 || throw(ArgumentError("TMetal_max > 0")) # Maximum metal temperature (K)
#     constraints_opt.DiaFan_max > 0 || throw(ArgumentError("DiaFan_max > 0")) # Maximum fan diameter (m)
#     
#     ac.parm[imRange,:] .= mission_req.range_des #Design flight range (m)
#     ac.options.ifuel = mission_req.idx_fuel #Fuel Index
#     ac.parg[igrhofuel] = mission_req.rho_fuel #Fuel Density (kg/m3)
#     ac.pare[iehvap, :, :] .= mission_req.hvap_fuel #Heat of Vaporization (J/kg)
#     ac.pare[iehvapcombustor, :, :] .= mission_req.hvap_fuel

"""
    make_obj(ac, parameters::AbstractVector{<:Parameter} ; constraints::AbstractVector{<:Constraint}=Vector{Constraint}(), print_every::Int=10, max_iter_sizing::Int=150, pen_failed_sizing::Float64=1e10)

`make_obj` constructs and returns an objective function for (PFEI flight) that will be fed to optimizer

!!!! details "🔃 Inputs and Outputs"
    **Inputs:**
        - `ac`: Baseline aircraft model for sizing
        - `parameters::AbstractVector{<:Parameter}`: parameters for optimization. (SI unit except for sweep angle using deg) (Unaltered by obj!, but `val` updated in the outer loop)
        - `constraints::AbstractVector{<:Constraint}=default empty`: constraints for optimization. Empty container of this type for unconstraint problem. (SI unit except for sweep angle using deg)
        - `print_every::Int=default`: every number of iterations before print out for the current optimization state (Performed by the returned objective function)
        - `max_iter_sizing::Int=default`: maximum number of iteration used for the sizing loop
        - `pen_failed_sizing::Float64=default`: penalty value for failed sizing process (to the scale of PFEI)
    
    **Outputs:**
        - `obj!`::a function: Objective function for optimizer. Size the aircraft and return the penalty. Also append the optimization history.
        - `hist`::OptHistory: Optimization history of test_param, penalty, PFEI, violations. All vector of history. returned by reference

!!! note "Behavior"
        - PFEI from mission one is assumed to be the main penalty variable for the returned `obj!` function
        - `obj!` returned will modify the input `ac` inplace and also will modify the returned `hist`
        - In the outer loop, if parameters length got changed, then the number of parameters expected by obj! here is also altered correspondingly. Beware.
        - All inputs are in SI unit except for sweep angle that use degree
        - For the constraints, maximum of value will be check against upper bound and minimum value against lower bound. No support for mean, or other statisics feature of data
"""
function make_obj(ac, parameters::AbstractVector{<:Parameter} ; constraints::AbstractVector{<:Constraint}=Vector{Constraint}(), print_every::Int=10, max_iter_sizing::Int=150, pen_failed_sizing::Float64=1e10)
    #### Size check
    isempty(parameters)    && throw(ArgumentError("`parameters` cannot be empty. Provide at least one optimization variable."))
    print_every >= 1       || throw(ArgumentError("`print_every` must be ≥ 1"))
    max_iter_sizing >= 10  || throw(ArgumentError("`max_iter_sizing` must be ≥ 10"))
    pen_failed_sizing > 0  || throw(ArgumentError("`pen_failed_sizing` must be > 0"))

    #### Construct an optimization history to be returned by reference for successive update
    hist = OptHistory() #History with emtpy entries

    #### Construct the objective function
    function obj!(x, grad)
        #### Sanity check
        (grad === nothing || isempty(grad)) || throw(ArgumentError("Gradient requested, but obj! has no gradient implementation.
                                              Use derivative-free NLopt algorithms (NM/DIRECT)."))
        (length(x) == length(parameters)) || throw(DimensionMismatch("#Param in by optimizer $(length(x)) not equal to the #Param expected $(length(parameters))"))

        #### Insert the parameters into the aircraft model 
        for (i_param, param_cur) in enumerate(parameters)
            setNestedProp_fromExpr!(ac, x[i_param]; field_path=param_cur.field_path, index=param_cur.index)
        end

        #### Test size the current case
        flgSuccessed = true
        try
            TASOPT.size_aircraft!(ac, iter=max_iter_sizing, printiter=false)
        catch e
            if e isa InterruptException #Unless user interruption
                rethrow()
            end
            flgSuccessed = false #Continue but mark current as failed sizing attempt
        end

        #### Primary penalty value
        main_penalty = flgSuccessed ? ac.parm[imPFEI, 1] : pen_failed_sizing #(J/J)
        
        #### Additional penalty because of the violation of the specified constraints
        add_penalty = 0.0
        violated_constraints = Vector{Constraint}() #Vector of constraints violated
        Wpay = Float64(ac.parg[igWpay]) #Used for additional penalty calculation
        for const_cur in constraints
            val_cur = getNestedProp_fromExpr(ac; field_path=const_cur.field_path, index=const_cur.index)
            # Check upper bound
            flag_const_added = false
            flag_const_added, add_penalty = Check_Upper_Constraint!(val_cur, ac, const_cur, flag_const_added, Wpay, add_penalty, violated_constraints)
            # Check lower bound (Will check if constrain has been added, if so, not duplicated constraint will be added to the violated list)
            flag_const_added, add_penalty = Check_Lower_Constraint!(val_cur, ac, const_cur, flag_const_added, Wpay, add_penalty, violated_constraints)
        end

        #### Final Penalty
        total_penalty = main_penalty + add_penalty

        ####Update the Optimization History
        push!(hist.test_param, copy(x))
        push!(hist.penalty, total_penalty)
        push!(hist.PFEI, main_penalty)
        push!(hist.violations, copy(violated_constraints))

        ####In-flight Printout
        InFlightPrintOut(hist, print_every)
        
        return total_penalty
    end
    return (; obj!, hist)
end

function Check_Upper_Constraint!(val_cur::Union{Real,AbstractArray}, ac, const_cur::Constraint, flag_const_added::Bool, Wpay::AbstractFloat, add_penalty::AbstractFloat, violated_constraints::Vector{Constraint})
    lim_up_cur = const_cur.lim_up
    if (lim_up_cur isa Expr)
        lim_up_cur = getNestedProp_fromExpr(ac; parm_sym=lim_up_cur) #Some cost, typically not prefer
    end
    if !isnothing(lim_up_cur)
        lim_up_cur = float(lim_up_cur) #Guard interger limit for one and eps
        val_max = (val_cur isa Real) ? val_cur : maximum(val_cur) #Guard maximum on noniterable
        sgn = iszero(lim_up_cur) ? one(lim_up_cur) : sign(lim_up_cur) #Extract the sign for near zero clamping
        lim_up_cur = (abs(lim_up_cur) < eps(lim_up_cur)) ? sgn*eps(lim_up_cur) : lim_up_cur #Clamping a near zero non-zero number
        if val_max > lim_up_cur + abs(lim_up_cur)*const_cur.eps_buff
            err_frac = val_max/lim_up_cur - 1.0
            pen_cur = const_cur.pen_sca * Wpay * err_frac^2
            add_penalty += pen_cur
            if !(flag_const_added)
                push!(violated_constraints, deepcopy(const_cur))
            end
            violated_constraints[end].value_max  = val_max
            violated_constraints[end].penalty_up = pen_cur
            violated_constraints[end].lim_up     = lim_up_cur 
            flag_const_added = true
        end
    end
    return flag_const_added, add_penalty
end

function Check_Lower_Constraint!(val_cur::Union{Real,AbstractArray}, ac, const_cur::Constraint, flag_const_added::Bool, Wpay::AbstractFloat, add_penalty::AbstractFloat, violated_constraints::Vector{Constraint})
    lim_lo_cur = const_cur.lim_lo
    if (lim_lo_cur isa Expr)
        lim_lo_cur = getNestedProp_fromExpr(ac; parm_sym=lim_lo_cur)
    end
    if !isnothing(lim_lo_cur)
        lim_lo_cur = float(lim_lo_cur) #Guard interger limit for one and eps
        val_min = (val_cur isa Real) ? val_cur : minimum(val_cur) #Guard maximum on noniterable
        sgn = iszero(lim_lo_cur) ? one(lim_lo_cur) : sign(lim_lo_cur) #Extract the sign for near zero clamping
        lim_lo_cur = (abs(lim_lo_cur) < eps(lim_lo_cur)) ? sgn*eps(lim_lo_cur) : lim_lo_cur #Clamping a near zero non-zero number
        if val_min < lim_lo_cur - abs(lim_lo_cur)*const_cur.eps_buff
            err_frac = 1.0 - val_min/lim_lo_cur
            pen_cur = const_cur.pen_sca * Wpay * err_frac^2
            add_penalty += pen_cur
            if !flag_const_added
                push!(violated_constraints, deepcopy(const_cur))
            end
            violated_constraints[end].value_min  = val_min
            violated_constraints[end].penalty_lo = pen_cur
            violated_constraints[end].lim_lo     = lim_lo_cur
            flag_const_added = true
        end
    end
    return flag_const_added, add_penalty
end

function InFlightPrintOut(hist::OptHistory, print_every::Int)
    cur_iter_optim = length(hist.penalty) #Number of iterations already run
    if (cur_iter_optim == 1 || cur_iter_optim % print_every == 0)
        println()
        @printf("Iter %4d | total_penalty = %.4f | PFEI = %.4f\n", cur_iter_optim, hist.penalty[end], hist.PFEI[end])
        println()
        @printf("Violates: ")
        for cur_violates in hist.violations[end]
            @printf("| %10s", string(cur_violates.name)*"⚠️")
        end
        println()
    end
end

"""
    optimize_singlePt_PFEI!(ac,
                            optimize_par::AbstractVector{<:Parameter};
                            mission_req::AbstractVector{<:Requirement}=Vector{Requirement}(),
                            constraints::AbstractVector{<:Constraint}=Vector{Constraint}(),
                            ftol_rel::Float64=1e-6,
                            max_iter_optim::Int=1000,
                            max_iter_sizing::Int=150,
                            print_every::Int=10,
                            pen_failed_sizing::Float64=1e10,
                            optimizer_type::Symbol=:LN_NELDERMEAD)

`optimize_singlePt_PFEI!` perform single sizing mission point optimization for minimum PFEI

    ***Inputs:***
        - ac: Baseline aircraft model for sizing (Need to have mission one sized)
        - optimize_par: parameters to be optimized (not empty) (updated in place) (constructed using constructor)
        - mission_req: requirements for the sizing mission (can empty[default mission]) (constructed using constructor)
        - constraints: constraints to be satisfied by the solution (can empty[unconstrained]) (constructed using constructor)
        - ftol_rel: relative tolerance to converge in optimization
        - max_iter_optim: maixmum optimization iterations (At least 3)
        - max_iter_sizing: maixmum TASOPT sizing iterations within each optimization iteration (At least 10)
        - print_every: print out frequency for optimizaion status
        - pen_failed_sizing: penalty to use in the case of TASOPT failed to size the aircraft (Relative to the scale of PFEI)
        - optimizer_type: optimization method: Ex. Local Search: :LN_NELDERMEAD or Global Search: :GN_DIRECT, :GN_DIRECT_L. (Only non-gradient base supported)
    
    ***Outputs***
        - status: Status of optimization: 
          Working cases: (:RECOVERED_FEASIBLE_FROM_HISTORY, :SUCCESS, :STOPVAL_REACHED, :FTOL_REACHED, :XTOL_REACHED, :MAXEVAL_REACHED, :MAXTIME_REACHED)
          Failed cases: (:NO_FEASIBLE_SOLUTION, :FAILURE, :INVALID_ARGS, :OUT_OF_MEMORY, :ROUNDOFF_LIMITED, :FORCED_STOP)
        - hist: Optimization history: {test_param::Vector{Vector{T}}, penalty::Vector{T}, PFEI::Vector{T}, violations::Vector{Vector{Constraint}}}
    ***Updated***
        - ac: Updated with the best solution if optimization succeeds. Return back to original status but with !!!New Mission!!! requirements if optimization failed.
        - optimize_par: The value `val` of the parameters are updated to the best solution if optimization succeeds. `val` is still the initial value if optimization failed.
                        Can be reused as starting guess for next adjacent case
    ***Behavior***
        - Need to sized the aicraft model before input.
        - Optimize_par, mission_req, and constraints all need to be in SI unit except for (deg used by sweep angle)
        - Optimize_par, mission_req, and constraints all need to be constructed using special constructor but not manual
        - Only support non-gradient base optimization method
"""
function optimize_singlePt_PFEI!(ac, optimize_par::AbstractVector{<:Parameter} ;
                                 mission_req::AbstractVector{<:Requirement}=Vector{Requirement}(),
                                 constraints::AbstractVector{<:Constraint}=Vector{Constraint}(),
                                 ftol_rel::Float64=1e-6, max_iter_optim::Int=1000, max_iter_sizing::Int=150,
                                 print_every::Int=10, pen_failed_sizing::Float64=1e10, optimizer_type::Symbol=:LN_NELDERMEAD)

    #### Size check (Only check parameters that are not checked by sub functions)
    if !(ac.is_sized[1])
        max_iter_sizing >= 10  || throw(ArgumentError("maximum number of sizing iterations must be >= 10"))
        @warn "The design point mission need to be sized before inputting. Here a new sizing process is performed."
        try
            TASOPT.size_aircraft!(ac, iter=max_iter_sizing, printiter=false)
        catch e
            @error "Initial sizing failed" exception=(e, catch_backtrace())
            rethrow()
        end
    end
    ftol_rel > 0           || throw(ArgumentError("Relative tolerance for optimization must be > 0"))
    max_iter_optim > 2    || throw(ArgumentError("maximum number of optimization interations must be > 2"))
    

    #### Implement the mission requirement into the aircraft model
    for miss_req_cur in mission_req
        setNestedProp_fromExpr!(ac, miss_req_cur.val; field_path=miss_req_cur.field_path, index=miss_req_cur.index)
    end

    #### Create an objective function and optimization history container
    obj!, hist = make_obj(ac, optimize_par ; constraints=constraints, print_every=print_every,
                          max_iter_sizing=max_iter_sizing, pen_failed_sizing=pen_failed_sizing)
                          #Call to obj! function modify ac and hist inplace

    #### Setup the optimized parameters
    # Reshape the optimization parameters
    upper_bounds = Float64.(getfield.(optimize_par, :bon_up))
    lower_bounds = Float64.(getfield.(optimize_par, :bon_lo))
    initial_step = Float64.(getfield.(optimize_par, :d_val))
    initial_gues = Float64.(getfield.(optimize_par, :val))
    number_param = length(optimize_par) #Number of parameters use to intiailize optimizer
    # Chek again the bounds and initial guess (In case the bounds and intial values are updated without the use of the constructor)
    any(upper_bounds .< lower_bounds) && error("Some upper bounds are below lower bounds")
    any(initial_step .<= 0) && error("Some initial step sizes are non-positive")
    initial_saved = copy(initial_gues) #This saved unclamped starting parameters are reused if the optimization failed
    if any((initial_gues .< lower_bounds) .| (initial_gues .> upper_bounds))
        @warn "Some initial guesses are out of bounds. Clamping them to within bounds."
        initial_gues = clamp.(initial_gues, lower_bounds, upper_bounds)
    end
    
    #### Optimization
    status = :FAILURE #Initialization
    try
        # Setup the optimizer
        opt               = NLopt.Opt(optimizer_type, number_param)
        opt.lower_bounds  = lower_bounds
        opt.upper_bounds  = upper_bounds
        opt.min_objective = obj!
        opt.initial_step  = initial_step
        opt.ftol_rel      = ftol_rel
        opt.maxeval       = max_iter_optim
        # Runing
        (_, _, status)    = NLopt.optimize(opt, initial_gues)
    catch e
        @error "Current optimization failed $(typeof(e)): $(e)"
    end

    #### Post-process the optimization results
    # Extract the best feasible solution
    bestSol = best_feasible(hist) #Name tuple of `index`, `test_param`, `penalty`, `PFEI`
    if isnothing(bestSol)
        println("No constraint satisfying solutions found, return to starting state")
        try
            obj!(initial_saved, nothing) #This will re-assign the starting value into the aircraft model, but the sizing will likely not going to work either.
        catch e
            @error "Failed to restore initial state or size aircraft with initial state but new mission requirements $(typeof(e)): $(e)"
        end
        if status in (:SUCCESS, :STOPVAL_REACHED, :FTOL_REACHED, :XTOL_REACHED, :MAXEVAL_REACHED, :MAXTIME_REACHED)
            status = :NO_FEASIBLE_SOLUTION
        end
    else
        println("Identified and setup the current best solution.")
        if status in (:FAILURE, :INVALID_ARGS, :OUT_OF_MEMORY, :ROUNDOFF_LIMITED, :FORCED_STOP)
            @warn "Using feasible solution from history despite optimizer termination status = $(status)"
            status = :RECOVERED_FEASIBLE_FROM_HISTORY
        end
        try
            obj!(bestSol.test_param, nothing) # This will re-assign the starting value into aircraft and size the aircraft to be best configuration
            setproperty!.(optimize_par, :val, bestSol.test_param) #This set the test parameters from the best run back into the optimization parameter container (Use as initial guess for next case)
        catch e
            @error "Failed to restore the best state found or size aircraft with the best state (Bizzard) $(typeof(e)): $(e)"
            status = :FAILURE
        end
    end

    return status, hist
end

end # module ObjectiveFactory