module ObjectiveFactory
export Constraint, Parameter, OptHistory, Requirement, optimize_singlePt_PFEI!, optimizer_wrapper_global_local, size_aircraft_w_param!,
       save_vec_struct_csv, load_csv_constraints, load_csv_parameters, load_csv_requirements, save_jld2, load_jld2
using TASOPT
using NLopt
using Printf
using CSV
using JLD2
using DataFrames
include(__TASOPTindices__)
include(joinpath(__TASOPTroot__,"utils","sensitivity.jl"))

"""
Container type for contraint for optimization
Use the corresponding constructor for it as additional field_path needs to be generated when constructed
If lim_up, or lim_lo are set to nothing, then their constrain will not be activated. If both nothing, the whole constraint is placeholder
"""
mutable struct Constraint{T<:AbstractFloat}
    name::Expr #Expression for state to be extract (Ex. :(parg[igVfuel]), :(parm[imVfuel, :]), :(pare[ierhofuel_driven,:,:]), :(fuselage.layout.cross_section.radius))
    pen_sca::T #Penalty scale
    lim_up::Union{T,Nothing,Expr} #Upper limit, trigger maximum modifier
    lim_lo::Union{T,Nothing,Expr} #Lower limit, trigger minimum modifier
    value_max::T #The maximum value of the constrainted variable (Driven)
    value_min::T #The minimum value of the constrainted variable (Driven)
    penalty_up::T #The penalty from upper bound violation (Driven)
    penalty_lo::T #The penalty from lower bound violation (Driven)
    field_path::Union{Vector,Nothing} #Will be generated by constructor (Driven)
    index::Any #(Driven)
    eps_buff::T #fraction buffer add and subtract from the limit to avoid roundoff error induced constraint unsatisfication
end

"""
    Constraint(name::Expr; pen_sca::Real=1.0, lim_up::Union{Real,Nothing,Expr}=nothing, lim_lo::Union{Real,Nothing,Expr}=nothing, eps_buff::Real=0.0)

Constructor for the `Constraint` type

    `name`: Expression for state to be extract (Ex. :(parg[igVfuel]), :(parm[imVfuel, :]), :(pare[ierhofuel_driven,:,:]), :(fuselage.layout.cross_section.radius))
            Remember the parameters should be mission 1 parameters for sizing
    `pen_sca`: pen_sca * 1.0 * fractional_exceed^2 -> added penalty ~ scale_of_PFEI
    `lim_up`: Upper limit, trigger maximum modifier if the value is an array
    `lim_lo`: Lower limit, This can be an `Expr` just like name, if the limit depends on solution. Such as the maximum takeoff weight and maximum fuel tank volume.
    `eps_buff:` fractional buffer used to check if value violate the constraint. Due to the iterative nature of sizing loop. Round off error can make near miss that always fail for example fuel volume constrain at R2.
"""
function Constraint(name::Expr; pen_sca::Real=1.0, 
                    lim_up::Union{Real,Nothing,Expr}=nothing, 
                    lim_lo::Union{Real,Nothing,Expr}=nothing,
                    eps_buff::Real=0.0)
    T = Float64
    field_path, index = format_params(expr_to_string(name))
    lim_up = (isnothing(lim_up) || (lim_up isa Expr)) ? lim_up : T(lim_up)
    lim_lo = (isnothing(lim_lo) || (lim_lo isa Expr)) ? lim_lo : T(lim_lo)
    (!isnothing(lim_up) && !(lim_up isa Expr)) && 
    (!isnothing(lim_lo) && !(lim_lo isa Expr)) && @assert(lim_up > lim_lo)
    pen_sca = T(pen_sca)
    eps_buff = T(eps_buff)
    @assert(pen_sca>=0.0)
    @assert(eps_buff>=0.0)
    return Constraint{T}(name, pen_sca, lim_up, lim_lo, T(NaN), T(NaN), zero(T), zero(T), field_path, index, eps_buff)
end

"""
Container type for parameters for optimization
Use the corresponding constructor for it as additional field_path needs to be generated when constructed
"""
mutable struct Parameter{T<:AbstractFloat}
    name::Expr #Expression for parameter (Ex. :(parg[igVfuel]), :(parm[imVfuel, :]), :(pare[ierhofuel_driven,:,:]), :(fuselage.layout.cross_section.radius))
    val::T #Either a initial guess val_0 will be used to stored the final optimized solution val_final
    bon_up::T #Upper bound for this parameter
    bon_lo::T #Lower bound
    d_val::T #Initial step size for this parameter
    field_path::Union{Vector,Nothing} #Will be generated by constructor (Driven)
    index::Any #(Driven)
end

"""
Constructor for the `Parameter` type
Parameter(name::Expr, val::Real, bon_up::Real, bon_lo::Real, d_val::Real)
    `name`: Expression for parameter (Ex. :(parg[igVfuel]), :(parm[imVfuel, :]), :(pare[ierhofuel_driven,:,:]), :(fuselage.layout.cross_section.radius))
            Remember the parameters should be mission 1 parameters for sizing
    `val`: a initial guess val_0 (Later will be overwritten into final optimized value)
    `bon_up`: Upper bound for this parameter (Maybe either gloabl bound or local bound)
    `bon_lo`: Lower bound
    `d_val`: Initial step size for this parameter
"""
function Parameter(name::Expr, val::Real, bon_up::Real, bon_lo::Real, d_val::Real)
    T = Float64
    field_path, index = format_params(expr_to_string(name))
    val = T(val) 
    bon_up = T(bon_up) 
    bon_lo = T(bon_lo) 
    d_val = T(d_val)
    @assert(bon_up>=val)
    @assert(val>=bon_lo)
    @assert(d_val>=0.0)
    return Parameter{T}(name, val, bon_up, bon_lo, d_val, field_path, index)
end

"""
Container type for the history of optimization
There is a trivial default construstor for it but typically it is returned by `make_obj` function
"""
mutable struct OptHistory{T<:AbstractFloat}
    test_param::Vector{Vector{T}}
    penalty::Vector{T}
    PFEI::Vector{T}
    violations::Vector{Vector{Constraint}}
end

"""Constructor for `OptHistory`"""
OptHistory() = OptHistory{Float64}(
    Vector{Vector{Float64}}(),
    Vector{Float64}(),
    Vector{Float64}(),
    Vector{Vector{Constraint}}()
)

"""
Container type for the mission requirement parameters
Use the corresponding constructor for it as additional field_path needs to be generated when constructed
"""
mutable struct Requirement{T<:Union{Real,AbstractArray{<:Real}}}
    name::Expr #Expression for requirement parameter (Ex. :(parg[igVfuel]), :(parm[imVfuel, :]), :(pare[ierhofuel_driven,:,:]), :(fuselage.layout.cross_section.radius))
    val::T #value to set
    field_path::Union{Vector,Nothing} #Will be generated by constructor (Driven)
    index::Any #(Driven)
end

"""
Constructor for the `Requirement` type
Requirement(name::Expr, val::Union{Real,AbstractArray{<:Real}})
    `name`: Expression for requirement parameter (Ex. :(parg[igVfuel]), :(parm[imVfuel, :]), :(pare[ierhofuel_driven,:,:]), :(fuselage.layout.cross_section.radius))
            Remember the parameters should be mission 1 parameters for sizing
    `val`: value you want to set into that parameter, accept broadcasting and elementwise assingment to an array.
"""
function Requirement(name::Expr, val::Union{Real,AbstractArray{<:Real}})
    field_path, index = format_params(expr_to_string(name))
    return Requirement{typeof(val)}(name,val,field_path,index)
end


"""
    best_feasible(hist_all::OptHistory)
`best_feasible` take a OptHistory and filter out a lowest penalty solution without violating any of the constraints

!!! details "🔃 Inputs and Outputs"
    **Inputs:**
        - `hist_all::OptHistory`: Optimization history

    **Outputs:**
        - nothing: if there were no feasible solution
        - named tuple (index, test_param, penalty, PFEI) for the best solution from the history
"""
function best_feasible(hist_all::OptHistory)
    idx = findall(v -> isempty(v), hist_all.violations)
    isempty(idx) && return nothing
    i = idx[argmin(hist_all.penalty[idx])]
    return (index=i, test_param=hist_all.test_param[i], penalty=hist_all.penalty[i], PFEI=hist_all.PFEI[i])
end
                              #Try to start with all 1 here actually
#penal_scale::Vector{Float64}=[25.0, 1.0, 1.0, 5.0, 5.0, 1.0, 10.0, 10.0]
#                       buffer[0     0    0      0   0.  0.  1e-4   1e-4]
#ac.wing.layout.span (Double check what goes in here)
#ac.parm[imlBF,1]
#ac.para[iagamV, ipclimbn, 1]
#maximum(ac.pare[ieTt3, :, 1])
#maximum(ac.pare[ieTmet1, :, 1])
#ac.parg[igdfan]
#ac.parm[imWTO, 1] -> ac.parg[igWMTO] as upper bound
#ac.parm[imVfuel, 1] -> ac.parg[igVfmax] as upper bound
#
#
#         ac.wing.layout.AR    = x[1]                                # Aspect Ratio 
#         ac.wing.layout.sweep = x[3]                                # Sweep angle (deg)
#         ac.wing.inboard.λ    = x[5]                                # Inner panel taper ratio
#         ac.wing.outboard.λ   = x[6]                                # Outer panel taper ratio
#         ac.wing.inboard.cross_section.thickness_to_chord  = x[7]   # Root thickness-to-chord ratio
#         ac.wing.outboard.cross_section.thickness_to_chord = x[8]   # Spanbreak thickness-to-chord ratio

#         # Update flight condition parameters
#         ac.para[iaCL, ipclimb1+1:ipdescentn-1, 1] .= x[2]       # Cruise lift coefficient
#         ac.para[iaalt, ipclimbn:ipcruise1, 1]     .= x[4]       # Cruise altitude
#         ac.para[iarcls, ipclimb2:ipdescent4, 1]   .= x[9]       # Break/root CL ratio = cls/clo
#         ac.para[iarclt, ipclimb2:ipdescent4, 1]   .= x[10]      # Tip/root CL ratio = clt/clo

#         # Update engine parameters
#         ac.pare[ieTt4, ipcruise1:ipcruise2, 1] .= x[11]         # Turbine inlet temperature
#         ac.pare[iepihc, ipcruise1, 1]           = x[12]         # High pressure compressor pressure ratio
#         ac.pare[iepif, ipcruise1, 1]            = x[13]         # Fan pressure ratio
#         ac.pare[iepilc, ipcruise1, 1]           = x[14]         # Low pressure compressor pressure ratio (fixed)
#         ac.pare[ieBPR, ipcruise1, 1]            = x[15]         # Bypass ratio
#     mission_req.range_des > 0 || throw(ArgumentError("Design flight range > 0"))
#     mission_req.rho_fuel > 0 || throw(ArgumentError("Fuel density > 0"))
#     mission_req.hvap_fuel >= 0 || throw(ArgumentError("Fuel heat of vaporization >= 0"))
#     # Constraints
#     constraints_opt.span_max > 0 || throw(ArgumentError("span_max > 0")) # Maximum span (m)
#     constraints_opt.lenField_max > 0 || throw(ArgumentError("lenField_max > 0")) # Maximum balanced field length (m)
#     constraints_opt.TOCGamma_min > 0 || throw(ArgumentError("TOCGamma_min > 0")) # Minimum top-of-climb flight angle (rad)
#     constraints_opt.Tt3_max > 0 || throw(ArgumentError("Tt3_max > 0")) # Maximum combustor inlet temperature (K)
#     constraints_opt.TMetal_max > 0 || throw(ArgumentError("TMetal_max > 0")) # Maximum metal temperature (K)
#     constraints_opt.DiaFan_max > 0 || throw(ArgumentError("DiaFan_max > 0")) # Maximum fan diameter (m)
#     
#     ac.parm[imRange,:] .= mission_req.range_des #Design flight range (m)
#     ac.options.ifuel = mission_req.idx_fuel #Fuel Index
#     ac.parg[igrhofuel] = mission_req.rho_fuel #Fuel Density (kg/m3)
#     ac.pare[iehvap, :, :] .= mission_req.hvap_fuel #Heat of Vaporization (J/kg)
#     ac.pare[iehvapcombustor, :, :] .= mission_req.hvap_fuel

"""
    make_obj(ac, parameters::AbstractVector{<:Parameter} ; constraints::AbstractVector{<:Constraint}=Vector{Constraint}(), print_every::Int=10, max_iter_sizing::Int=150, pen_failed_sizing::Float64=100.0)

`make_obj` constructs and returns an objective function for (PFEI flight) that will be fed to optimizer

!!!! details "🔃 Inputs and Outputs"
    **Inputs:**
        - `ac`: Baseline aircraft model for sizing (Passed by copy)
        - `parameters::AbstractVector{<:Parameter}`: parameters for optimization. (SI unit except for sweep angle using deg) (Unaltered by obj! call)
        - `constraints::AbstractVector{<:Constraint}=default empty`: constraints for optimization. Empty container of this type for unconstraint problem. (SI unit except for sweep angle using deg)
        - `print_every::Int=default`: every number of iterations before print out for the current optimized state (Performed by obj! call)
        - `max_iter_sizing::Int=default`: maximum number of iteration used for the sizing loop
        - `pen_failed_sizing::Float64=default`: penalty value for failed sizing process (to the scale of PFEI)
    
    **Outputs:**
        - `obj!`::a function: Objective function for optimizer. Only return a penalty value and modify the optimization history. 
                  A copy of aircraft model is changed within obj! call BUT does not affect the model initially inputted into make_obj function. 
                  The initially inputted model is used to refresh the aircraft model used by obj! before every call for deterministic behavior.
        - `hist`::OptHistory: Optimization history for only succeed sizing case, containing test_param, penalty, PFEI, violations. returned by reference and will be modified by obj! call.

!!! note "Behavior"
        - PFEI from mission one is assumed to be the main penalty variable for the returned `obj!` function
        - Call to `obj!` will modify the returned `hist` by reference. However, the `ac` changed within obj! call does not affect the ac for make_obj input or the ac outside of the function call. (passed and reset by copy)
        - In the outer loop, if parameters length got changed, then the number of parameters expected by obj! here is also altered correspondingly. Beware.
        - All inputs are in SI unit except for sweep angle that use degree
        - For the constraints, maximum of value will be check against upper bound and minimum value against lower bound. No support for mean, or other statisics feature of data
"""
function make_obj(ac, parameters::AbstractVector{<:Parameter} ; constraints::AbstractVector{<:Constraint}=Vector{Constraint}(), print_every::Int=10, max_iter_sizing::Int=150, pen_failed_sizing::Float64=100.0)
    #### Size check
    isempty(parameters)    && throw(ArgumentError("`parameters` cannot be empty. Provide at least one optimization variable."))
    print_every >= 1       || throw(ArgumentError("`print_every` must be ≥ 1"))
    max_iter_sizing >= 10  || throw(ArgumentError("`max_iter_sizing` must be ≥ 10"))
    pen_failed_sizing > 0  || throw(ArgumentError("`pen_failed_sizing` must be > 0"))

    #### Construct an optimization history to be returned by reference for successive update
    hist = OptHistory() #History with empty entries

    #### make a backup
    ac_bak = deepcopy(ac)
    
    #### make a iteration counter
    count = 0

    #### Construct the objective function
    function obj!(x, grad)
        #### Always reset back to the same initial aircraft model for the current optimization attempt
        ac = deepcopy(ac_bak)

        #### Update current function call count
        count += 1
        println("Current Objective Function Call # $(count)")

        #### Sanity check
        (grad === nothing || isempty(grad)) || throw(ArgumentError("Gradient requested, but obj! has no gradient implementation.
                                            Use derivative-free NLopt algorithms (NM/DIRECT)."))
        (length(x) == length(parameters)) || throw(DimensionMismatch("#Param in by optimizer $(length(x)) not equal to the #Param expected $(length(parameters))"))

        #### Insert the parameters into the aircraft model 
        for (i_param, param_cur) in enumerate(parameters)
            setNestedProp_fromExpr!(ac, x[i_param]; field_path=param_cur.field_path, index=param_cur.index)
        end

        #### Test sizing the current case
        flgSuccessed = true
        try
            TASOPT.size_aircraft!(ac, iter=max_iter_sizing, printiter=false)
        catch e
            if e isa InterruptException #Unless user interruption
                rethrow()
            end
            flgSuccessed = false #Continue but mark current as failed sizing attempt
        end

        #### Primary penalty value
        main_penalty = flgSuccessed ? ac.parm[imPFEI, 1] : pen_failed_sizing #(J/J)
        
        #### Additional penalty because of the violation of the specified constraints
        add_penalty = 0.0
        violated_constraints = Vector{Constraint}() #Vector of constraints violated
        if flgSuccessed
            for const_cur in constraints
                val_cur = getNestedProp_fromExpr(ac; field_path=const_cur.field_path, index=const_cur.index)
                # Check upper bound
                flag_const_added = false
                flag_const_added, add_penalty = Check_Upper_Constraint!(val_cur, ac, const_cur, flag_const_added, add_penalty, violated_constraints)
                # Check lower bound (Will check if constrain has been added, if so, not duplicated constraint will be added to the violated list)
                flag_const_added, add_penalty = Check_Lower_Constraint!(val_cur, ac, const_cur, flag_const_added, add_penalty, violated_constraints)
            end
        end

        #### Final Penalty
        total_penalty = main_penalty + add_penalty

        #### Store history only if sizing were successful
        if flgSuccessed
            # Update the Optimization History
            push!(hist.test_param, copy(x))
            push!(hist.penalty, total_penalty)
            push!(hist.PFEI, main_penalty)
            push!(hist.violations, violated_constraints)
        end

        #### In-flight Printout
        InFlightPrintOutBest(hist, print_every, count)
        
        return total_penalty
    end
    return (; obj!, hist)
end

function Check_Upper_Constraint!(val_cur::Union{Real,AbstractArray}, ac, const_cur::Constraint, flag_const_added::Bool, add_penalty::AbstractFloat, violated_constraints::Vector{Constraint})
    lim_up_cur = const_cur.lim_up
    if (lim_up_cur isa Expr)
        lim_up_cur = getNestedProp_fromExpr(ac; parm_sym=lim_up_cur) #Some cost, typically not prefer
    end
    if !isnothing(lim_up_cur)
        lim_up_cur = float(lim_up_cur) #Guard interger limit for one and eps
        val_max = (val_cur isa Real) ? val_cur : maximum(val_cur) #Guard maximum on noniterable
        sgn = iszero(lim_up_cur) ? one(lim_up_cur) : sign(lim_up_cur) #Extract the sign for near zero clamping
        lim_up_cur = (abs(lim_up_cur) < eps(lim_up_cur)) ? sgn*eps(lim_up_cur) : lim_up_cur #Clamping a near zero non-zero number
        if val_max > lim_up_cur + abs(lim_up_cur)*const_cur.eps_buff
            err_frac = val_max/lim_up_cur - 1.0
            pen_cur = const_cur.pen_sca * err_frac^2
            add_penalty += pen_cur
            if !(flag_const_added)
                push!(violated_constraints, deepcopy(const_cur))
            end
            violated_constraints[end].value_max  = val_max
            violated_constraints[end].penalty_up = pen_cur
            violated_constraints[end].lim_up     = lim_up_cur 
            flag_const_added = true
        end
    end
    return flag_const_added, add_penalty
end

function Check_Lower_Constraint!(val_cur::Union{Real,AbstractArray}, ac, const_cur::Constraint, flag_const_added::Bool, add_penalty::AbstractFloat, violated_constraints::Vector{Constraint})
    lim_lo_cur = const_cur.lim_lo
    if (lim_lo_cur isa Expr)
        lim_lo_cur = getNestedProp_fromExpr(ac; parm_sym=lim_lo_cur)
    end
    if !isnothing(lim_lo_cur)
        lim_lo_cur = float(lim_lo_cur) #Guard interger limit for one and eps
        val_min = (val_cur isa Real) ? val_cur : minimum(val_cur) #Guard maximum on noniterable
        sgn = iszero(lim_lo_cur) ? one(lim_lo_cur) : sign(lim_lo_cur) #Extract the sign for near zero clamping
        lim_lo_cur = (abs(lim_lo_cur) < eps(lim_lo_cur)) ? sgn*eps(lim_lo_cur) : lim_lo_cur #Clamping a near zero non-zero number
        if val_min < lim_lo_cur - abs(lim_lo_cur)*const_cur.eps_buff
            err_frac = 1.0 - val_min/lim_lo_cur
            pen_cur = const_cur.pen_sca * err_frac^2
            add_penalty += pen_cur
            if !flag_const_added
                push!(violated_constraints, deepcopy(const_cur))
            end
            violated_constraints[end].value_min  = val_min
            violated_constraints[end].penalty_lo = pen_cur
            violated_constraints[end].lim_lo     = lim_lo_cur
            flag_const_added = true
        end
    end
    return flag_const_added, add_penalty
end

function InFlightPrintOutBest(hist::OptHistory, print_every::Int, count::Int)
    if ((length(hist.penalty) > 0) && (count % print_every == 0))
        idx_cur_best = argmin(hist.penalty)
        println()
        @printf("Iter %4d | Current Best Penalty = %.4f | Current Best PFEI = %.4f\n",
                 count,     hist.penalty[idx_cur_best],   hist.PFEI[idx_cur_best])
        println()
        @printf("Violates: ")
        for cur_violates in hist.violations[idx_cur_best]
            @printf("| %10s", string(cur_violates.name)*"⚠️")
        end
        println()
    end
end

function InFlightPrintOut(hist::OptHistory, print_every::Int)
    cur_iter_optim = length(hist.penalty) #Number of iterations already run
    if (cur_iter_optim == 1 || cur_iter_optim % print_every == 0)
        println()
        @printf("Iter %4d | total_penalty = %.4f | PFEI = %.4f\n", cur_iter_optim, hist.penalty[end], hist.PFEI[end])
        println()
        @printf("Violates: ")
        for cur_violates in hist.violations[end]
            @printf("| %10s", string(cur_violates.name)*"⚠️")
        end
        println()
    end
end

"""These are the statuses for NLOpt optimization results"""
const success_statuses = (:SUCCESS, :STOPVAL_REACHED, :FTOL_REACHED, :XTOL_REACHED, :MAXEVAL_REACHED, :MAXTIME_REACHED)
const failure_statuses = (:FAILURE, :INVALID_ARGS, :OUT_OF_MEMORY, :ROUNDOFF_LIMITED, :FORCED_STOP)

"""
    optimize_singlePt_PFEI!(ac,
                            optimize_par::AbstractVector{<:Parameter};
                            mission_req::AbstractVector{<:Requirement}=Vector{Requirement}(),
                            constraints::AbstractVector{<:Constraint}=Vector{Constraint}(),
                            ftol_rel::Float64=1e-6,
                            max_iter_optim::Int=1000,
                            max_iter_sizing::Int=150,
                            print_every::Int=10,
                            pen_failed_sizing::Float64=100.0,
                            optimizer_type::Symbol=:LN_NELDERMEAD)

`optimize_singlePt_PFEI!` perform single sizing mission point optimization for minimum PFEI

    ***Inputs:***
        - ac: Baseline aircraft model for sizing (No Change in place) (Recommend to have mission one sized, but also auto-size if unsized)
        - optimize_par: parameters to be optimized (not empty) (:val updated in place if succeeded, left at input state if failed) (constructed using constructor)
        - mission_req: requirements for the sizing mission (can be empty[native mission]) (No Change in place) (constructed using constructor)
        - constraints: constraints to be satisfied by the solution (can be empty[unconstrained]) (No Change in place) (constructed using constructor)
        - ftol_rel: relative tolerance to converge in optimization
        - max_iter_optim: maixmum optimization iterations (At least 3)
        - max_iter_sizing: maixmum TASOPT sizing iterations within each optimization iteration (At least 10)
        - print_every: print out frequency for optimizaion status
        - pen_failed_sizing: penalty to use in the case of TASOPT failed to size the aircraft (Relative to the scale of PFEI)
        - optimizer_type: optimization method: Ex. Local Search: :LN_NELDERMEAD or Global Search: :GN_CRS2_LM, :GN_DIRECT. (Only non-gradient base supported)
    
    ***Outputs***
        - status: Status of optimization: 
          Success cases: (:RECOVERED_FEASIBLE_FROM_HISTORY, :SUCCESS, :STOPVAL_REACHED, :FTOL_REACHED, :XTOL_REACHED, :MAXEVAL_REACHED, :MAXTIME_REACHED)
          Fail cases: (:NO_FEASIBLE_SOLUTION, :FAILURE, :INVALID_ARGS, :OUT_OF_MEMORY, :ROUNDOFF_LIMITED, :FORCED_STOP)
        - hist: Optimization history: {test_param::Vector{Vector{T}}, penalty::Vector{T}, PFEI::Vector{T}, violations::Vector{Vector{Constraint}}}
    
    ***Updated***
        - optimize_par: The value `:val` of the parameters are updated to the best feasible solution found if optimization succeeded. `:val` is still the initial value if optimization failed.

    ***Behavior***
        - Recommend sizing the aicraft model before input.
        - Optimize_par, mission_req, and constraints all need to be in SI unit except for (deg used by sweep angle)
        - Optimize_par, mission_req, and constraints all need to be constructed using special constructor but not manual
        - Only support non-gradient base optimization method
        - Always unchange the starting constraints, mission requirements, aircraft model state
        - Update the value inside optimization parametrs, status, and history of optimization (only succeed sizing)

"""
function optimize_singlePt_PFEI!(ac, optimize_par::AbstractVector{<:Parameter} ;
                                 mission_req::AbstractVector{<:Requirement}=Vector{Requirement}(),
                                 constraints::AbstractVector{<:Constraint}=Vector{Constraint}(),
                                 ftol_rel::Float64=1e-6, max_iter_optim::Int=1000, max_iter_sizing::Int=150,
                                 print_every::Int=10, pen_failed_sizing::Float64=100.0, optimizer_type::Symbol=:LN_NELDERMEAD)
    #### make a copy of the input aircraft model state to ensure model is unaltered by function call for successive deterministic behavior
    ac = deepcopy(ac)
    
    #### Size check (Only check parameters that are not checked by sub functions)
    if !(ac.is_sized[1])
        max_iter_sizing >= 10  || throw(ArgumentError("maximum number of sizing iterations must be >= 10"))
        @warn "The design point mission need to be sized before inputting. Here a new sizing process is performed."
        try
            TASOPT.size_aircraft!(ac, iter=max_iter_sizing, printiter=false)
        catch e
            @error "Initial sizing failed" exception=(e, catch_backtrace())
            rethrow()
        end
    end
    ftol_rel > 0       || throw(ArgumentError("Relative tolerance for optimization must be > 0"))
    max_iter_optim > 2 || throw(ArgumentError("maximum number of optimization interations must be > 2"))
    
    #### Implement the mission requirement into the aircraft model
    for miss_req_cur in mission_req
        setNestedProp_fromExpr!(ac, miss_req_cur.val; field_path=miss_req_cur.field_path, index=miss_req_cur.index)
    end

    # The optionally sized aircraft model with current mission requirements inserted will be the model copy
    # reused by the optimizer to as a baseline to test implementing different design parameter.

    #### Create an objective function and optimization history container
    (; obj!, hist) = make_obj(ac, optimize_par ; constraints=constraints, print_every=print_every,
                              max_iter_sizing=max_iter_sizing, pen_failed_sizing=pen_failed_sizing)
                              #Call to obj! function only modify hist inplace. NO change to parameters, constraint, mission requirement, and aircraft model.

    #### Setup the optimized parameters
    # Reshape the optimization parameters
    upper_bounds = Float64.(getfield.(optimize_par, :bon_up)) #Boardcasting extraction by copy
    lower_bounds = Float64.(getfield.(optimize_par, :bon_lo))
    initial_step = Float64.(getfield.(optimize_par, :d_val))
    initial_gues = Float64.(getfield.(optimize_par, :val))
    number_param = length(optimize_par) #Number of parameters use to intiailize optimizer
    # Chek again the bounds and initial guess (In case the bounds and intial values are updated without the use of the constructor)
    any(upper_bounds .<= lower_bounds) && error("Some upper bounds are below or equal to lower bounds")
    any(initial_step .<= 0) && error("Some initial step sizes are non-positive")
    if any((initial_gues .< lower_bounds) .| (initial_gues .> upper_bounds))
        @warn "Some initial guesses are out of bounds. Clamping them to within bounds."
        initial_gues = clamp.(initial_gues, lower_bounds, upper_bounds)
    end
    
    #### Optimization
    status = :FAILURE #Initialization
    try
        # Setup the optimizer
        opt               = NLopt.Opt(optimizer_type, number_param)
        opt.lower_bounds  = lower_bounds
        opt.upper_bounds  = upper_bounds
        opt.min_objective = obj!
        opt.initial_step  = initial_step
        opt.ftol_rel      = ftol_rel
        opt.maxeval       = max_iter_optim
        # Runing
        (_, _, status)    = NLopt.optimize(opt, initial_gues)
    catch e
        e isa InterruptException && rethrow()
        @error "Current optimization failed $(typeof(e)): $(e)"
    end

    #### Post-process the optimization results
    # Extract the best feasible solution
    bestSol = best_feasible(hist) #Name tuple of `index`, `test_param`, `penalty`, `PFEI`
    if isnothing(bestSol)
        println("No constraint satisfying solutions found, \nOptimize_par is left at its initial state. \nAircraft model is insid the current function call may change but NOT changing the input model to the function due to passed by copy")
        if status in success_statuses #Ex. FTOL is reached but no feasible solution were found.
            status = :NO_FEASIBLE_SOLUTION
        end
    else
        println("Identified and setup the current best solution.")
        if status in failure_statuses #Ex. Maximum memory reached, but some feasible constraint satisfying solution have beed tested.
            @warn "Using feasible solution from history despite optimizer termination status = $(status)"
            status = :RECOVERED_FEASIBLE_FROM_HISTORY
        end
        setproperty!.(optimize_par, :val, bestSol.test_param) #This set the test parameters from the best run back into the optimization parameter container (Use as mild initial guess for next case)
    end

    return status, hist
end

"""
    adjust_bounds!(optimize_par::AbstractVector{<:Parameter},
                   global_bounds_par::AbstractVector{<:Parameter};
                   frac_edge_trigger::AbstractFloat=0.15,
                   frac_edge_expanded::AbstractFloat=0.3,
                   eps::AbstractFloat=1e-10)

`adjust_bounds!` adjusts the local bounds to the current best solution for next iteration

    **Inputs:**
        - optimize_par: Have current best sol in :val, and local bounds :bon_up, :bon_lo may or may not be updated in place
        - global_bounds_par: only need to provide the hard global bounds :bon_up and :bon_lo to clip the updated local bound
        - frac_edge_trigger(def): fractional local span as a threshold distance if solution is too close to either bounds, bound expansion process will be trigger
        - frac_edge_expanded(def): fractional local span to expand from the current solution to the limiting bound side. Need to be larger than that for trigger to avoid repeated boundary expansion.
        - eps(def): a small fraction to detect if global bounds are touched
    
    **Outputs:**
        - flg_bod_cha::Bool: flag true if the local bounds changes.
    
    **Behavior:**
        - Solution must be within or on the edge of the global bounds at least.
        - Solution can be outside of the local bound
        - Local bounds can be outside of global bound
        - Span of the local bound will be kept unchanged by this updating process
        - Span of the local bound has to be smaller than global span
        - Initial step size will remain unchanged because the span is unchanged
        - Does NOT accept placeholder type of fixed parameter (Ex. those with upper bound ~= lower bound and initial dx == 0.0)
        - flg_bod_cha is directly obained from comparing old versus new bounds
"""
function adjust_bounds!(optimize_par::AbstractVector{<:Parameter},
                        global_bounds_par::AbstractVector{<:Parameter};
                        frac_edge_trigger::AbstractFloat=0.15,
                        frac_edge_expanded::AbstractFloat=0.3,
                        eps::AbstractFloat=1e-10)
    
    #### Size check
    0 <= frac_edge_trigger || throw(ArgumentError("Boundary expansion triggering margin $(frac_edge_trigger) smaller than zero"))
    frac_edge_trigger < frac_edge_expanded || throw(ArgumentError("Boundary expansion triggering margin $(frac_edge_trigger) needs to be tighter than expansion margin $(frac_edge_expanded)"))
    frac_edge_expanded <= 0.5 || throw(ArgumentError("Boundary expansion fraction $(frac_edge_expanded) should not be more than 50% to the limiting side"))
    eps >= 0 || throw(ArgumentError("eps $(eps) smaller than zero"))
    length(optimize_par) == length(global_bounds_par) || throw(ArgumentError("Dimension of global bounds $(length(global_bounds_par)) not matching with dimension of local bounds $(length(optimize_par))"))
        
    #### Loop through each field to adjust bounds
    flg_bod_cha = false
    for idx in eachindex(optimize_par)
        # Extract span and check for validity
        sol_cur = optimize_par[idx].val
        local_low_cur = optimize_par[idx].bon_lo
        local_upp_cur = optimize_par[idx].bon_up
        local_span_cur = local_upp_cur-local_low_cur
        local_span_cur > 0 || throw(ErrorException("Zero width local bounds span detected $(local_span_cur)"))
        global_low_cur = global_bounds_par[idx].bon_lo
        global_upp_cur = global_bounds_par[idx].bon_up
        global_span_cur = global_upp_cur-global_low_cur
        global_span_cur > 0 || throw(ErrorException("Non-positive global span detected $(global_span_cur)"))
        eps_close = global_span_cur*eps
        (local_span_cur <= global_span_cur + eps_close) || throw(ErrorException("Local span $(local_span_cur) larger than global span $(global_span_cur)"))
        (sol_cur >= local_low_cur  - eps_close && sol_cur <= local_upp_cur  + eps_close) || @warn "Current solution $(sol_cur) is out of local bounds $(local_low_cur) to $(local_upp_cur). This is only expected if initially setup a placeholder local bound just to provide a fixed local span"
        (sol_cur >= global_low_cur - eps_close && sol_cur <= global_upp_cur + eps_close) || throw(DomainError(sol_cur,"Current solution $(sol_cur) is out of global bounds $(global_low_cur) to $(global_upp_cur)."))

        # Update the bounds
        frac_lower_margin_cur = (sol_cur-local_low_cur)/local_span_cur #Could be negative or bigger than unity if local bounds are not catching the solution
        if frac_lower_margin_cur <= frac_edge_trigger
            if local_low_cur <= global_low_cur + eps_close
                local_low_cur = global_low_cur
            else
                local_low_cur = sol_cur - frac_edge_expanded*local_span_cur #so long as local span smaller than global
                local_low_cur = clamp(local_low_cur, global_low_cur, global_upp_cur-local_span_cur) #this ensure local bounded by global
            end
            local_upp_cur = local_low_cur + local_span_cur
        elseif frac_lower_margin_cur >= (1.0-frac_edge_trigger)
            if local_upp_cur >= global_upp_cur - eps_close
                local_upp_cur = global_upp_cur
            else
                local_upp_cur = sol_cur + frac_edge_expanded*local_span_cur
                local_upp_cur = clamp(local_upp_cur, global_low_cur+local_span_cur, global_upp_cur)
            end
            local_low_cur = local_upp_cur - local_span_cur
        else
            if local_low_cur <= global_low_cur + eps_close
                local_low_cur = global_low_cur
                local_upp_cur = local_low_cur + local_span_cur
            elseif local_upp_cur >= global_upp_cur - eps_close
                local_upp_cur = global_upp_cur
                local_low_cur = local_upp_cur - local_span_cur
            end #Local search may trigger these repeatedly but that should not trigger the boundary change flag
                #Unless somehow NLOpt drift the bounds definition which is unlikely
        end

        # Check if any of the bound is changed
        if (!isapprox(local_low_cur, optimize_par[idx].bon_lo; atol=eps_close, rtol=eps) ||
            !isapprox(local_upp_cur, optimize_par[idx].bon_up; atol=eps_close, rtol=eps))
            flg_bod_cha = true
            # Assign the new bounds
            optimize_par[idx].bon_lo = local_low_cur
            optimize_par[idx].bon_up = local_upp_cur
        end
    end

    return flg_bod_cha
end

"""
    optimizer_wrapper_global_local(ac, optimize_par::AbstractVector{<:Parameter},
                                   global_bond::AbstractVector{<:Parameter}; miss_req::AbstractVector{<:Requirement}=Vector{Requirement}(), constraints::AbstractVector{<:Constraint}=Vector{Constraint}(),
                                   ftol_rel::Float64=1e-6, max_iter_sizing::Int=150, print_every::Int=10, pen_failed_sizing::Float64=100.0,
                                   frac_edge_trigger::AbstractFloat=0.15, frac_edge_expanded::AbstractFloat=0.3,
                                   optimizer_global::Symbol=:GN_CRS2_LM,   max_iter_glo::Int=50000,   span_glo_to_loc::AbstractFloat=0.25, run_global::Bool=false,
                                   optimizer_local::Symbol=:LN_NELDERMEAD, max_iter_loc_C::Int=500,   max_round_loc_C::Int=100,
                                                                           max_iter_loc_F::Int=10000, max_round_loc_F::Int=10,             max_retry::Int = 10)

`optimizer_wrapper_global_local` wraps around the single point optimizer to create a global then local search algorithm, along with adaptive bounds movement.

    **Inputs**
        (Mandatory)
        - ac: Baseline aircraft model for sizing (Unchanged by call) (Recommended to have mission one sized)
        - optimize_par: (Unchanged by call) Have current initial guess in :val, 
                        and local bounds if directly run local optimization or 
                        global bound if start with global solution. (constructed using constructor) (Step size for local span in mind)
        - global_bond:  (Unchanged by call)only need to provide the hard global bounds. (Clip local bound movement) (constructed using constructor)
        
        (Optional)
        [Common regardless operating mode]
        - miss_req(def): (Unchanged by call) requirements for the sizing mission (can empty[default mission]) (constructed using constructor)
        - constraints(def): (Unchanged by call) constraints to be satisfied by the solution (can empty[unconstrained]) (constructed using constructor)
        - ftol_rel(def): relative tolerance to converge in optimization
        - max_iter_sizing(def): maixmum TASOPT sizing iterations within each optimization iteration (At least 10)
        - print_every(def): print out frequency for optimizaion status
        - pen_failed_sizing(def): penalty to use in the case of TASOPT failed to size the aircraft (Relative to the scale of PFEI)
        
        [Common regardless operating mode but for adaptive bounds adjustment]
        - frac_edge_trigger(def): fractional local span as a threshold distance if solution is too close to either bounds, bound expansion process will be trigger
        - frac_edge_expanded(def): fractional local span to expand from the current solution to the limiting bound side. Need to be larger than that for trigger to avoid repeated boundary expansion.
            
        [Parameters only for local runs]
        - optimizer_local(def): local optimization method. Ex. :LN_NELDERMEAD (Only non-gradient base)
        - max_iter_loc_C(def): maixmum optimization iterations for coarse local run
        - max_round_loc_C(def): maximum bound refinement loops for coarse local run
        - max_iter_loc_F(def): maixmum optimization iterations for fine local run
        - max_round_loc_F(def): maximum bound refinement loops for fine local run
        - max_retry(def) maximum number of reattempts if failed in local runs

        [Parameters only for global runs]
        - optimizer_global(def): global optimization method. Ex. :GN_CRS2_LM, :GN_DIRECT, (Only non-gradient base)
        - max_iter_glo(def): maximum optimization iterations for global run at the beginning
        - span_glo_to_loc(def): span_local / span_global for creating a local bound after the global run
        - run_global(def): Activate initial global run. Also, if activated, global search retry will not be performed anymore.

    **Outputs**
        - optimize_par::AbstractVector{<:Parameter}: optimized parameters (:val) with updated local bounds (:bon_up and :bon_lo). Can be one of the known best state or input state.
        - status::Symbol: NLOpt resulted status for optimization. (Can be success, fail, or :Unknown state) :Unknown state only if input state were returned.
        - hist::OptHistory{test_param, penalty, PFEI, violations}. (Can be empty if no feasible solution found or return input state)

    **Behavior**
        - This function does not change any input variable in place
        - Step size provided in parameters should be based on the local span in mind. For example, if first run global, then dx should be based on global span * frac_loc_to_glo_span
        - Local span remains unaltered throughout the adaptive process
        - This function does not accept fixed placeholder parameter
        - Aircraft model recommended to be sized first before input
        - Only accept non-gradient based optimization method
        - Algorithm: 
            1.Global run once from global bound to get a starting solution (Opt-in)
            2.Setup a good starting local bound from the global round solution or input.
            3.Iteratively run local coarse search with small number of maximum iterations.
            4.Recenter local bounds around solution from coarse search. (Help bounds quickly converge)
            5.Local bounds converge
            6.Iteratively run local fine search with large number of maximum iteraitons.
            7.Iterate fine search if bounds starts changing again.
            8.If bounds converge and fine run get a good solution. Then good, return
            ----- During coarse and fine local run ----
            9.If fail in each phase, re-iterate multiple times with perturbed starting state
            10.If global search has not been attempted, re-run the whole solver with global search first.
            11.If none of the above works, retract to last known best state and go to next phase or output.
"""

function optimizer_wrapper_global_local(ac, optimize_par::AbstractVector{<:Parameter},
                                        global_bond::AbstractVector{<:Parameter}; miss_req::AbstractVector{<:Requirement}=Vector{Requirement}(), constraints::AbstractVector{<:Constraint}=Vector{Constraint}(),
                                        ftol_rel::Float64=1e-6, max_iter_sizing::Int=150, print_every::Int=10, pen_failed_sizing::Float64=100.0,
                                        frac_edge_trigger::AbstractFloat=0.15, frac_edge_expanded::AbstractFloat=0.3,
                                        optimizer_global::Symbol=:GN_CRS2_LM,   max_iter_glo::Int=50000,   span_glo_to_loc::AbstractFloat=0.25, run_global::Bool=false,
                                        optimizer_local::Symbol=:LN_NELDERMEAD, max_iter_loc_C::Int=500,   max_round_loc_C::Int=100,
                                                                                max_iter_loc_F::Int=10000, max_round_loc_F::Int=10,             max_retry::Int = 10)
    #### Size check
    ((span_glo_to_loc > 0.0) && (span_glo_to_loc < 1.0)) || throw(ArgumentError("fractional local span to global span $(span_glo_to_loc) should be between 0 to 1"))
    (max_round_loc_C > 0) || throw(ArgumentError("maximum iterations of local coarse runs  $(max_round_loc_C) should be bigger than 0"))
    (max_round_loc_F > 0) || throw(ArgumentError("maximum iterations of local fine runs $(max_round_loc_F) should be bigger than 0"))
    (max_retry >= 0) || throw(ArgumentError("maximum number of reattempt $(max_retry) should be bigger or equal to 0"))
    (length(optimize_par) == length(global_bond)) || throw(ArgumentError("#parameters $(length(optimize_par)) should match with #globalbounds $(length(global_bond))"))
    # ftol_rel, max_iter_sizing, print_every, pen_failed_sizing, max_iter_xxxx checked by optimize_singlePt_PFEI!
    # frac_edge_trigger, frac_edge_expanded checked by adjust_bounds!

    #### Pass inputs by copies to avoid inplace modifications
    optimize_par = deepcopy(optimize_par)
    status = :Unknown #Unkown is neither fail nor success criteria
    hist = OptHistory() #Starting condition is always unknown convergence status with empty history

    #### Create backup state for failsafe mechanism
    optimize_par_bak = deepcopy(optimize_par)
    status_bak = :Unknown
    hist_bak = OptHistory()

    #### Phase One: Global Optimization
    if run_global
        # Set the starting boundary to the global boundaries (Update boundary)
        for (idx_par, opt_par_cur) in enumerate(optimize_par)
            opt_par_cur.bon_up =  global_bond[idx_par].bon_up #For global search, always use the total global bound
            opt_par_cur.bon_lo =  global_bond[idx_par].bon_lo
            ((opt_par_cur.val <= opt_par_cur.bon_up) && (opt_par_cur.val >= opt_par_cur.bon_lo)) || throw(DomainError(opt_par_cur.val, "Initial guess $(opt_par_cur.val) shuold be within bounds from $(opt_par_cur.bon_lo) to $(opt_par_cur.bon_up)"))
        end

        # Try the optimization process
        try
            status, hist = optimize_singlePt_PFEI!(ac, optimize_par; mission_req=miss_req, constraints=constraints, #(Update value)
                                                   ftol_rel=ftol_rel, max_iter_optim=max_iter_glo, max_iter_sizing=max_iter_sizing,
                                                   print_every=print_every, pen_failed_sizing=pen_failed_sizing, optimizer_type=optimizer_global)
        catch e
            (e isa InterruptException) && rethrow(e)
            status = :FAILURE
        end

        # Post-process
        if status in success_statuses
            # Create a local bound from the global bound
            for opt_par_cur in optimize_par
                # Here only set a local span, only require the solution to be within the global bound. Adjust_bounds! will correct the local bound location. 
                opt_par_cur.bon_up = opt_par_cur.bon_lo + span_glo_to_loc*(opt_par_cur.bon_up - opt_par_cur.bon_lo)
            end
            adjust_bounds!(optimize_par, global_bond; frac_edge_trigger=frac_edge_trigger, frac_edge_expanded=frac_edge_expanded) #(Update boundary)
            
            # Store the good solution into backup for failsafe
            optimize_par_bak = deepcopy(optimize_par)
            status_bak = status
            hist_bak = hist #No need to copy hist because it were not modified in place in this function call
        else
            # No retry for global cause nothing much except for tuning boundary can be done
            println("Global optimizatin fails. Go back to the input states. Proceed to local optimization using directly the global bound")
            optimize_par = deepcopy(optimize_par_bak) #History and status are not required for the following run (save cost)
            for (idx_par, opt_par_cur) in enumerate(optimize_par)
                opt_par_cur.bon_up =  global_bond[idx_par].bon_up
                opt_par_cur.bon_lo =  global_bond[idx_par].bon_lo
            end
        end
    end

    #### Global run succeeded or skipped. Check for bounds and values before local optimizations. (Only need one check as bound update ensure consistency)
    for (idx_par, opt_par_cur) in enumerate(optimize_par)
        (opt_par_cur.bon_up <= global_bond[idx_par].bon_up) || throw(DomainError(opt_par_cur.bon_up, "Local upper bound $(opt_par_cur.bon_up) shuold not be larger than global $(global_bond[idx_par].bon_up)"))
        (opt_par_cur.bon_lo >= global_bond[idx_par].bon_lo) || throw(DomainError(opt_par_cur.bon_lo, "Local lower bound $(opt_par_cur.bon_lo) shuold not be lower  than global $(global_bond[idx_par].bon_lo)"))
        ((opt_par_cur.val <= opt_par_cur.bon_up) && (opt_par_cur.val >= opt_par_cur.bon_lo)) || throw(DomainError(opt_par_cur.val, "Initial guess $(opt_par_cur.val) should be within bounds from $(opt_par_cur.bon_lo) to $(opt_par_cur.bon_up)"))
    end

    #### Phase Two: Local Coarse Optimization
    # Initialization
    count_coarse = 0
    count_retry = 0
    bound_change = true
    
    # Loop through bound change
    while (bound_change && (count_coarse < max_round_loc_C))
        # Update counter
        count_coarse += 1

        # Try the optimization process
        try
            status, hist = optimize_singlePt_PFEI!(ac, optimize_par; mission_req=miss_req, constraints=constraints, #(Update value)
                                                   ftol_rel=ftol_rel, max_iter_optim=max_iter_loc_C, max_iter_sizing=max_iter_sizing,
                                                   print_every=print_every, pen_failed_sizing=pen_failed_sizing, optimizer_type=optimizer_local)
        catch e
            (e isa InterruptException) && rethrow(e)
            status = :FAILURE
        end

        # Post-process
        if status in success_statuses
            # Update the local bound
            bound_change = adjust_bounds!(optimize_par, global_bond; frac_edge_trigger=frac_edge_trigger, frac_edge_expanded=frac_edge_expanded)
            
            # Store the good solution into backup for failsafe
            optimize_par_bak = deepcopy(optimize_par)
            status_bak = status
            hist_bak = hist #Again, rebind is good enough
        else
            # Try 1. rerun, 2. global rerun, 3. return the last known good solution
            if count_retry < max_retry
                # Get back to the last known good solution (Only need parameter for retry)
                optimize_par = deepcopy(optimize_par_bak)

                # Randomly perturb the solution as initial try
                for opt_par_cur in optimize_par
                    δ = 0.001 * (2.0 * rand() - 1.0) #0.1% randome perturbation
                    opt_par_cur.val *= (1.0 + δ)
                    opt_par_cur.val = clamp(opt_par_cur.val, opt_par_cur.bon_lo, opt_par_cur.bon_up)
                end

                # Setup retry process
                max_round_loc_C += 1 #Rerun process create new iteration out of the original limitation
                count_retry += 1 #Rerun might happens multiple times non-consecutively, but the total number of rerun allowed in each phase is fixed
                bound_change = true #Treate each rerun as fake bound update
            elseif !run_global
                # Attempt to use rerun the whole solution process with a global search to reconverge the solution
                # This is only trigger if and only if the current optimization did not involve global search, though sometimes it is still helpful if method are stoichastics, but assume not much impact.
                # optimize_par_bak is still used here but not much impact, as global_bond is the key for this rerun
                (optimize_par_retry, status_retry, hist_retry) = optimizer_wrapper_global_local(ac, optimize_par_bak,
                                                                 global_bond; miss_req=miss_req, constraints=constraints,
                                                                 ftol_rel=ftol_rel, max_iter_sizing=max_iter_sizing, print_every=print_every, pen_failed_sizing=pen_failed_sizing,
                                                                 frac_edge_trigger=frac_edge_trigger, frac_edge_expanded=frac_edge_expanded,
                                                                 optimizer_global=optimizer_global, max_iter_glo=max_iter_glo,     span_glo_to_loc=span_glo_to_loc, run_global=true,
                                                                 optimizer_local=optimizer_local,   max_iter_loc_C=max_iter_loc_C, max_round_loc_C=max_round_loc_C,
                                                                                                    max_iter_loc_F=max_iter_loc_F, max_round_loc_F=max_round_loc_F, max_retry=max_retry)
                
                # Post-process (Due to recursive nature. No point to repeated the process by continue from here if recursive call failed)
                if status_retry in success_statuses
                    println("reattempt global search succeeded. Return the best solution from there directly.")
                    return (optimize_par_retry, status_retry, hist_retry)
                else
                    println("Reattempt global search failed. Return the outer function last known best solution. Dont know which one is better.")
                    return (optimize_par_bak, status_bak, hist_bak)
                end
            else
                println("Local search failed. Run out of retry and have already done global search. Take the last best solution and directly goes to fine search.")
                optimize_par = deepcopy(optimize_par_bak)
                break #Break out because 1. Sometime fine search allows converged solution due to longer run. 2. No point to keep the same starting guess rerun local (same staled result).
            end
        end
    end

    #### Phase Three: Local Fine Optimization
    # Initialization
    count_fine = 0
    count_retry = 0
    bound_change = true
    
    # Loop through bound change
    while (bound_change && (count_fine < max_round_loc_F))
        # Update counter
        count_fine += 1

        # Try the optimization process
        try
            status, hist = optimize_singlePt_PFEI!(ac, optimize_par; mission_req=miss_req, constraints=constraints, #(Update value)
                                                   ftol_rel=ftol_rel, max_iter_optim=max_iter_loc_F, max_iter_sizing=max_iter_sizing,
                                                   print_every=print_every, pen_failed_sizing=pen_failed_sizing, optimizer_type=optimizer_local)
        catch e
            (e isa InterruptException) && rethrow(e)
            status = :FAILURE
        end

        # Post-process
        if status in success_statuses
            # Update the local bound
            bound_change = adjust_bounds!(optimize_par, global_bond; frac_edge_trigger=frac_edge_trigger, frac_edge_expanded=frac_edge_expanded)
            
            # Store the good solution into backup for failsafe
            optimize_par_bak = deepcopy(optimize_par)
            status_bak = status
            hist_bak = hist #Again, rebind is good enough
        else
            # Try 1. rerun, 2. global rerun, 3. return the last known good solution
            if count_retry < max_retry
                # Get back to the last known good solution (Only need parameter for retry)
                optimize_par = deepcopy(optimize_par_bak)

                # Randomly perturb the solution as initial try
                for opt_par_cur in optimize_par
                    δ = 0.001 * (2.0 * rand() - 1.0) #0.1% randome perturbation
                    opt_par_cur.val *= (1.0 + δ)
                    opt_par_cur.val = clamp(opt_par_cur.val, opt_par_cur.bon_lo, opt_par_cur.bon_up)
                end

                # Setup retry process
                max_round_loc_F += 1 #Rerun process create new iteration out of the original limitation
                count_retry += 1 #Rerun might happens multiple times non-consecutively, but the total number of rerun allowed in each phase is fixed
                bound_change = true #Treate each rerun as fake bound update
            elseif !run_global
                # Attempt to use rerun the whole solution process with a global search to reconverge the solution
                # This is only trigger if and only if the current optimization did not involve global search, though sometimes it is still helpful if method are stoichastics, but assume not much impact.
                # optimize_par_bak is still used here but not much impact, as global_bond is the key for this rerun
                (optimize_par_retry, status_retry, hist_retry) = optimizer_wrapper_global_local(ac, optimize_par_bak,
                                                                 global_bond; miss_req=miss_req, constraints=constraints,
                                                                 ftol_rel=ftol_rel, max_iter_sizing=max_iter_sizing, print_every=print_every, pen_failed_sizing=pen_failed_sizing,
                                                                 frac_edge_trigger=frac_edge_trigger, frac_edge_expanded=frac_edge_expanded,
                                                                 optimizer_global=optimizer_global, max_iter_glo=max_iter_glo,     span_glo_to_loc=span_glo_to_loc, run_global=true,
                                                                 optimizer_local=optimizer_local,   max_iter_loc_C=max_iter_loc_C, max_round_loc_C=max_round_loc_C,
                                                                                                    max_iter_loc_F=max_iter_loc_F, max_round_loc_F=max_round_loc_F, max_retry=max_retry)
                
                # Post-process (Due to recursive nature. No point to repeated the process by continue from here if recursive call failed)
                if status_retry in success_statuses
                    println("reattempt global search succeeded. Return the best solution from there directly.")
                    return (optimize_par_retry, status_retry, hist_retry)
                else
                    println("Reattempt global search failed. Return the outer function last known best solution. Dont know which one is better.")
                    return (optimize_par_bak, status_bak, hist_bak)
                end
            else
                println("Local search failed. Run out of retry and have already done global search. Take the last best solution and directly return them.")
                return (optimize_par_bak, status_bak, hist_bak)
            end
        end
    end
    
    return (optimize_par, status, hist) # return for successful case
end

"""
    size_aircraft_w_param!(ac; mission_req::AbstractVector{<:Requirement}=Vector{Requirement}(),
                           parameters::AbstractVector{<:Parameter}=Vector{Parameter}(), 
                           max_iter_sizing::Int=150, printiter::Bool=false)

`size_aircraft_w_param!` sizes an aircraft based on a provided mission_requirements and parameters

    **Inputs**
        - `ac`: TASOPT aircraft model, can be unsized (Modified in place)
        - `mission_req`(def): mission requirement (can be empty) (requirements within :val)
        - `parameters` (def): design parameters (can be empty) (parameters within :val)
        - `max_iter_sizing` (def): maximum number of sizing loop
        - `printiter` (def): whether to print out the sizing process
    
    **Outputs**
        - `flgSuccessed`::Bool: whether sizing were successful
    
    **Behavior**
        - aircraft model modified in place
"""
function size_aircraft_w_param!(ac; mission_req::AbstractVector{<:Requirement}=Vector{Requirement}(),
                                parameters::AbstractVector{<:Parameter}=Vector{Parameter}(), 
                                max_iter_sizing::Int=150, printiter::Bool=false)

    #### Implement the mission requirement into the aircraft model
    for miss_req_cur in mission_req
        setNestedProp_fromExpr!(ac, miss_req_cur.val; field_path=miss_req_cur.field_path, index=miss_req_cur.index)
    end
    
    #### Insert the design variables into the aircraft model 
    for param_cur in parameters
        setNestedProp_fromExpr!(ac, param_cur.val; field_path=param_cur.field_path, index=param_cur.index)
    end

    #### Try to size the aircraft
    flgSuccessed = true
    try
        TASOPT.size_aircraft!(ac, iter=max_iter_sizing, printiter=printiter)
    catch e
        if e isa InterruptException #Unless user interruption
            rethrow()
        end
        flgSuccessed = false
    end

    return flgSuccessed
end

####### Type conversion helper functions. Used to store TASOPT data into and from csv

"""From Expr conversion to String"""
function _expr_to_str(ex::Expr)
    return sprint(Base.show_unquoted, ex)
end

"""From String conversion to Expr"""
function _str_to_expr(s::AbstractString)
    return Meta.parse(s)
end

"""
    _encode_union(x::Union{Nothing,Expr,Real})

`_encode_union` encodes several values of different datatype into strings
For real: Only bool and int are specially handled
          Rational, Abstract Irrational, and Float all handled as Float64
    
    **Inputs**
        - x: Variable for conversion
    
    **Outputs**
        - (string of data type(nothing, expr, int, float), data in string form)

"""
function _encode_union(x::Union{Nothing,Expr,Real})
    if x === nothing
        return ("nothing", "")
    elseif x isa Expr
        return ("expr", _expr_to_str(x))
    else #x isa Real
        if x isa Bool
            return ("bool", string(x))
        elseif x isa Integer
            return ("int", string(x))
        else
            x = Float64(x)
            return ("float", string(x))
        end
    end
end

"""
    _decode_union(data_val, data_type::AbstractString)

`_decode_union` corresponds to _encode_union to reconvert the stored string form data back to
their original form. For Real, only conversion back to bool, int, and float64 are assumed.
    
    **Inputs**
        - data_val: The raw value read from CSV
        - data_type: the type of data
    
    **Outputs**
        - data_val in the converted form

"""
function _decode_union(data_val, data_type::AbstractString)
    #### Reformat data type
    data_type = lowercase(strip(data_type))
    #### Conversion
    if data_type == "nothing"
        return nothing
    elseif data_type == "expr"
        return _str_to_expr(string(data_val))
    elseif data_type == "bool"
        return parse(Bool, string(data_val))
    elseif data_type == "int"
        return parse(Int, string(data_val))
    else #float
        return parse(Float64, string(data_val))
    end
end

"""
    save_vec_struct_csv(path::AbstractString, data::AbstractVector; fieldIgnore::AbstractVector{<:AbstractString}=["field_path", "index"])

`save_vec_struct_csv` saves Constraint, Requirement, and Parameter into csv file

    **Inputs**
        - `path`: Path of csv to save. "xxxx.csv"
        - `data`: One of the three type (Vector of of the three types)
        - `fieldIgnore`: fields to not save due to complexity of the data
    
"""
function save_vec_struct_csv(path::AbstractString, data::AbstractVector; fieldIgnore::AbstractVector{<:AbstractString}=["field_path", "index"])
    #### Size check
    if isempty(data)
        @warn "No data to save"
        return nothing
    end
    
    #### Process ignore fields
    ignore = Set(Symbol.(fieldIgnore))
    keep_fields = Vector{Symbol}()
    for f in fieldnames(typeof(data[1]))
        if !(f in ignore)
            push!(keep_fields, f)
        end
    end
    
    #### Extract data into container
    rows = Vector{NamedTuple}(undef, length(data))
    for (idx, sub_data) in enumerate(data)
        # Collector for all fields
        pairs_row = Vector{Pair{Symbol,String}}() #Both the data type and data are stored in string form
        for f in keep_fields
            v = getfield(sub_data, f)
            try
                # Store the current field
                val_kind, val = _encode_union(v)
                push!(pairs_row, Symbol(f, "_type")  => val_kind)
                push!(pairs_row, Symbol(f, "_value") => val)
            catch err
                throw(ArgumentError("Data conversion for field $(f) failed: $(typeof(err)), $err"))
            end
        end
        rows[idx] = (; pairs_row...) # Conver to a named tuple for storage
    end

    #### Save to csv
    CSV.write(path, DataFrame(rows))
    return nothing
end

"""
    load_csv_constraints(path::AbstractString)

`load_csv_constraints` loads a vector of constraints from a csv file

    **Inputs**
        - path: the path of the csv
    
    **Outputs**
        - constraint_out::Vector{Constraint}: The mission constraints

"""
function load_csv_constraints(path::AbstractString)
    #### Read in the csv
    df = CSV.read(path, DataFrame)

    #### Read in data to reconstruct the constraint
    constraint_out = Constraint[]
    for row in eachrow(df)
        name = _decode_union(row.name_value, string(row.name_type))
        pen_sca = _decode_union(row.pen_sca_value, string(row.pen_sca_type))
        lim_up = _decode_union(row.lim_up_value, string(row.lim_up_type))
        lim_lo = _decode_union(row.lim_lo_value, string(row.lim_lo_type))
        eps_buff = _decode_union(row.eps_buff_value, string(row.eps_buff_type))
        push!(constraint_out, Constraint(name; pen_sca=pen_sca, lim_up=lim_up, lim_lo=lim_lo, eps_buff=eps_buff))
    end
    return constraint_out
end

"""
    load_csv_parameters(path::AbstractString)

`load_csv_parameters` loads a vector of parameters from a csv file

    **Inputs**
        - path: the path of the csv
    
    **Outputs**
        - parameters_out::Vector{Parameter}: The design parameters

"""
function load_csv_parameters(path::AbstractString)
    #### Read in the csv
    df = CSV.read(path, DataFrame)

    #### Read in data to reconstruct the parameters
    parameters_out = Parameter[]
    for row in eachrow(df)
        name = _decode_union(row.name_value, string(row.name_type))
        val = _decode_union(row.val_value, string(row.val_type))
        bon_up = _decode_union(row.bon_up_value, string(row.bon_up_type))
        bon_lo = _decode_union(row.bon_lo_value, string(row.bon_lo_type))
        d_val = _decode_union(row.d_val_value, string(row.d_val_type))
        push!(parameters_out, Parameter(name, val, bon_up, bon_lo, d_val))
    end
    return parameters_out
end

"""
    load_csv_requirements(path::AbstractString)

`load_csv_requirements` loads a vector of requirements from a csv file

    **Inputs**
        - path: the path of the csv
    
    **Outputs**
        - requirements_out::Vector{Requirement}: The mission requirements

"""
function load_csv_requirements(path::AbstractString)
    #### Read in the csv
    df = CSV.read(path, DataFrame)

    #### Read in data to reconstruct the requirements
    requirements_out = Requirement[]
    for row in eachrow(df)
        name = _decode_union(row.name_value, string(row.name_type))
        val = _decode_union(row.val_value, string(row.val_type))
        push!(requirements_out, Requirement(name, val))
    end
    return requirements_out
end

"""
    save_jld2(path::AbstractString, h)

`save_jld2` quickly save whatever object into jld2 file. Ex. save_jld2("history.jld2", hist)

    **Inputs**
        - path: the file path to save to ***.jld2
        - h: the object
"""
function save_jld2(path::AbstractString, h)
    jldopen(path, "w") do f
        f["data"] = h
    end
    return nothing
end

"""
    load_jld2(path::AbstractString, ::Type{H})

`load_jld2` quickly load an object from jld2 file. Ex. hist2 = load_jld2("history.jld2", OptHistory{Float64})

    **Inputs**
        - path: the file path to load from to ***.jld2
        - ::Type{H}: Concrete type of the object to load into
    
    **OUtputs**
        - x::Type{H}: the object created from jld2
"""
function load_jld2(path::AbstractString, ::Type{H}) where {H}
    x = load(path, "data")
    x isa H || throw(ArgumentError("Expected $H, got $(typeof(x))"))
    return x
end

end # module ObjectiveFactory